version: '3.5'
services:
  nginx:
    container_name: cv-nginx
    build:
      context: docker/nginx
    volumes:
      - ./:/var/www/html
    ports:
      - "80:80"
    depends_on:
      - php-fpm

  php-fpm:
    container_name: cv-php-fpm
    build:
      context: docker/php7.4-fpm
    volumes:
      - ./:/var/www/html
    depends_on:
      - mysql

  mysql:
    container_name: cv-mysql
    image: mysql:5.7
    volumes:
      - ./var/mysql/dbdata/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=deliveryroot"
      - "MYSQL_USER=deliveryroot"
      - "MYSQL_PASSWORD=deliveryroot"
      - "MYSQL_DATABASE=delivery-db"
    ports:
      - "3306:3306"
